- chunks/unplaced.gff3-08
> annotate Uncx-2

- chunks/unplaced.gff3-06
> annotated Emx-1 and Emx-2

- chunks/unplaced.gff3-04
> annotate Msxlx and NK2.2

- chunks/unplaced.gff3-03
> annotate Phox

- chunks/unplaced.gff3-02
> annotate Msx, NK4, Bari, ANTP-4, and NK6

- chunks/unplaced.gff3-01
> annotate TALE-I, Zeb, Xlox, Gsx, and Dmbx

- chunks/unplaced.gff3-00
> annotate Arx-2

- chunks/scaffold_9.gff3-01
> annotate TALE-IV-1 and PRD-III

- chunks/scaffold_8.gff3-02
> annotate Shox

- chunks/scaffold_8.gff3-01
> annotate Pknox-2 and Repo

- chunks/scaffold_7.gff3-03
> annotate Prop

- chunks/scaffold_7.gff3-02
> annotate TALE-IV-2

- chunks/scaffold_7.gff3-01
> annotate Gsc,  NK2.1, and PRD-V-2

- chunks/scaffold_7.gff3-00
> annotate Six3/6, Otx, Lopx, Six4/5, and Meis

- chunks/scaffold_6.gff3-02
> annotate Pbx-1

- chunks/scaffold_6.gff3-01
> annotate Lhx6/8, Prrx, Lmx, and Barhl

- chunks/scaffold_6.gff3-00
> annotate Lhx3/4

- chunks/scaffold_5.gff3-02
> annotate NK3

- chunks/scaffold_5.gff3-01
> annotate PRD-V-1 and Tlx

- chunks/scaffold_5.gff3-00
> annotate NK1-1, NK1-2, NK5, Lbx, Noto, ANTP-3, NK7, Hhex, and Vax

- chunks/scaffold_4.gff3-02
> annotate Pou2 and Pknox-1

- chunks/scaffold_4.gff3-00
> annotate Bsx

- chunks/scaffold_30.gff3
> annotate Evx

- chunks/scaffold_3.gff3-03
> annotate TALE-2b

- chunks/scaffold_3.gff3-02
> annotate Irx-1, Irx-2, and Irx-3

- chunks/scaffold_3.gff3-01
> annotate Zfhx

- chunks/scaffold_29.gff3
> annotate Cdx

- chunks/scaffold_23.gff3
> annotate Cux

- chunks/scaffold_22.gff3
> annotate Meox, Nedx, and Dlx

- chunks/scaffold_21.gff3
> annotate Mkx

- chunks/scaffold_2.gff3-06
> annotate Drgx

- chunks/scaffold_2.gff3-04
> annotate Uncx

- chunks/scaffold_16.gff3
> annotate Cers-2, Cers-3, Vsx-1, Vsx-2, and Prox

- chunks/scaffold_14.gff3
> annotate En and TALE-XVIII

- chunks/scaffold_12.gff3-00
> annotate Mnx and Ro

- chunks/scaffold_11.gff3-01
> annotate Hlx and ANTP-2

- chunks/scaffold_10.gff3-01
> annotate Dbx-1 and Dbx-2

- chunks/scaffold_10.gff3-00
> annotate Onecut, Pitx-1, Pitx-2, Pitx-3, and Pitx-4

- chunks/scaffold_1.gff3-09
> annotate Tgif and Cers-1

- chunks/scaffold_1.gff3-08
> annotate Pou6, PRD-3, Pou3, and PRD-1

- chunks/scaffold_1.gff3-07
> annotate Pou6

- chunks/scaffold_1.gff3-03
> annotate Hmbox

- chunks/scaffold_1.gff3-00
> annotate Pou4

- chunks/scaffold_9.gff3-00
Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models. Already on NCBI: GenBank: ADK38671.1
> Annotate smoothened

- chunks/scaffold_10.gff3-01
Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene models Already on NCBI: GenBank: ALS30892.1
> Annotate sFRP-3/4

- chunks/scaffold_10.gff3-00
Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene models Already on NCBI: GenBank: ALS30891.1
> Annotate sFRP-1/2/5

- chunks/scaffold_1.gff3-09
gene model search, and subsequent solid phylogenetic analysis using metazoan gene models Already on NCBI: GenBank: ANS60434.1
> Annotate Frizzled-9/10

- chunks/scaffold_12.gff3-00
Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene models Already on NCBI: GenBank: ALS30889.1
> Annotate Frizzled-5/8

- docs/PULL_REQUEST_TEMPLATE/gene_name.md
formalising the discussion with @Benedikt-Duerr
> PR template for gene name proposals

- chunks/scaffold_17.gff3
NCBI sequence of hes2 from Gazave et al 2014
> annotate hes2
