chunks/scaffold_12.gff3-00

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models including all tubulin related genes. Pdum has one zeta Tubulin. Current annotations of spiralian tubulins do not distinguish between the related delta and zeta Tubulins, and zeta Tubulins are wrongly annotated as delta Tubulin. Best Blast hit at NCBI: CAH1788254.1 unnamed protein product [Owenia fusiformis]. Platynereis genome encodes at least 9 alpha tubulin genes (potentially several more), seven beta-tubulin genes (maybe a couple more), one gamma, one delta (missing in this version!), one epsilon, and one zeta tubulin gene.

Annotate Tubulin zeta

---

chunks/scaffold_20.gff3

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models including all tubulin related genes. Pdum has one epsilon Tubulin. Best Blast hit at NCBI: tubulin epsilon chain-like [Liolophura japonica], a mollusc. Platynereis genome encodes at least 9 alpha tubulin genes (potentially several more), seven beta-tubulin genes (maybe a couple more), one gamma, one delta (missing in this version!), one epsilon, and one zeta tubulin gene.

Annotate Tubulin epsilon

---

chunks/scaffold_1.gff3-09

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models including all tubulin related genes. Pdum has one gamma Tubulin. Best Blast hit at NCBI: Tubulin gamma-1 chain [Lamellibrachia satsuma].

Annotate Tubulin gamma

---

chunks/scaffold_7.gff3-00

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Pdum has one foxQ1, one Q2, one Q2C, and at least six related genes QM1 to QM6. Some are not currently found in the genome. This gene model corresponds to FoxQM6. QM1 to QM6 are our suggested name for these genes that radiated in annelids. It will require more work within annelids to clarify the orthologous relationships among these genes.

Annotate FoxQM6

---

chunks/scaffold_11.gff3-02

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Pdum has one foxQ1, one Q2, one Q2C, and at least six related genes QM1 to QM6. Some are not currently found in the genome. This gene model corresponds to FoxQM5, and might be incomplete. QM1 to QM6 are our suggested name for these genes that radiated in annelids. It will require more work within annelids to clarify the orthologous relationships among these genes.

Annotate FoxQM5

---

chunks/scaffold_11.gff3-02

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Pdum has one foxQ1, one Q2, one Q2C, and at least six related genes QM1 to QM6. Most are not currently found in the genome. This gene model corresponds to FoxQM3, and is a partial fragment. QM1 to QM6 are our suggested name for these genes that radiated in annelids. It will require more work within annelids to clarify the orthologous relationships among these genes.

Annotate FoxQM3

---

chunks/scaffold_7.gff3-02

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Pdum has one foxQ1, one Q2, one Q2C, and at least six related genes QM1 to QM6. Most are not currently found in the genome. This gene model corresponds to FoxQM2, and is a partial fragment. QM1 to QM6 are our suggested name fors these genes that radiated in annelids. It will require more work within annelids to clarify the orthologous relationships among these genes.

Annotate FoxQM2

---

chunks/scaffold_2.gff3-06

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Pdum has one foxQ1, one Q2, one Q2C, and at least six related genes QM1 to QM6. Most are not currently found in the genome. This gene model corresponds to FoxQM1, our suggested name for these genes that radiated in annelids. It will require more work within annelids to clarify the orthologous relationships among these genes.

Annotate FoxQM1

---

chunks/scaffold_18.gff3

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxN1/4 gene. Currently not on NCBI. 2nd Best hit: Forkhead box protein N4 [Lamellibrachia satsuma]

Annotate FoxN1/4

---

chunks/scaffold_10.gff3-02

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxM gene. Currently not on NCBI. Best hit: uncharacterized protein

Annotate FoxM

---

chunks/unplaced.gff3-03

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxJ2/3 gene, and one foxJ1 gene. Currently not on NCBI. Best hit: forkhead box protein J2 isoform X4 [Lingula anatina]

Annotate FoxJ2/3

---

chunks/scaffold_2.gff3-00

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxJ1, and another foxJ2/3 gene. Found in NCBI AHI16248.1 annotated as FoxJ which is wrong.

Annotate FoxJ1

---

chunks/scaffold_16.gff3

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxG gene. Found in NCBI ADG26725.1

Annotate FoxG

---

chunks/unplaced.gff3-00

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxD gene. Currently not on NCBI. Best hit: forkhead box protein D1 [Magallana gigas]

Annotate FoxD

---

chunks/scaffold_3.gff3-01

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxC gene. Currently not on NCBI. Best hit: Halitosis asinina forkhead C2B-like.

Annotate FoxC

---

chunks/scaffold_15.gff3

Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models. Currently not on NCBI This is one of a number of smaller gene models with a Frizzled-related Cysteine-Rich Domain (CRD) mostly not deeply evolutionary conserved.

Annotate FzCRD-3

---

chunks/scaffold_3.gff3-02

Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models. Currently not on NCBI This is one of a number of smaller gene models with a Frizzled-related Cysteine-Rich Domain (CRD) mostly not deeply evolutionary conserved.

Annotate FzCRD-2

---

chunks/unplaced.gff3-03

Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models. Already on NCBI: GenBank: ALS30893.1 This is one of a number of smaller gene models with a Frizzled-related Cysteine-Rich Domains (CRDs) mostly not deeply evolutionary conserved.

Annotate FzCRD-1

---

chunks/scaffold_6.gff3-01

Solid phylogenetic analysis using metazoan orthologs Alternative name could be Lhx 6/8 
I could not find islet, Lhx2/9, and Lhx3/4b in the current genome though solidly supported by gene models from transcriptomes. Lhx3/4b is a more recent duplication but can be also found in the closely related Alitta virens genome next to Lhx3/4a.

Annotate arrowhead

---

chunks/scaffold_2.gff3-04

Annotation: Ras-GTPase-activating protein-binding-like protein
**Annotator:**  [Marlen Brodbeck](https://orcid.org/0009-0006-6502-2560)
**Gene name:** Ras-GTPase-activating protein-binding-like protein
**Gene nomenclature:** []()
**Source/ NCBI GeneBank ID:** [MT795155.1](https://www.ncbi.nlm.nih.gov/nuccore/MT795155.1)
**Annotated XLOC:** XLOC_025966
**Annotation process:**
- Obtained mRNA sequence from NCBI
- Mapped to P. dum. transcriptome assembly v021 using BLASTn (Jékely Lab): [Results](https://jekelylab.ex.ac.uk/blast/a52af0c0-6cbc-4363-87c9-406e39398e3d#Query_1_hit_1)
- Best hit (TCONS_00068049 XLOC_025966) > blastx on NCBI > confirmed
**Comments:** /

Annotation: Ras-GTPase-activating protein-binding-like protein

---

chunks/scaffold_7.gff3-01

NCBI sequence of foxA was mapped (form 1) to the v0.2.1 transcriptome via Jekely BLAST web server; best hit was confirmed to the member of the Fox (Forkhead box protein B) family via reserve BLAST search on NCBI
[1] https://pubmed.ncbi.nlm.nih.gov/30566266/

annotate foxA

---

chunks/scaffold_10.gff3-00

NCBI sequence of tektin4 (from [1]) was mapped to the v021 transcriptome via Jekely BLAST webserver; best hit was confirmed to be member of the TEKTIN family via reverse BLAST search on NCBI
[1]https://www.sciencedirect.com/science/article/pii/S0012160623001380

annotate tektin4

---

chunks/scaffold_10.gff3-02

NCBI sequence of tektin3/5b (from [1]) was mapped to the v021 transcriptome via Jekely BLAST webserver; best hit was confirmed to be member of the TEKTIN family via reverse BLAST search on NCBI
[1]https://www.sciencedirect.com/science/article/pii/S0012160623001380

annotate tektin3/5b

---

chunks/scaffold_1.gff3-03

NCBI sequence of tektin2 (from [1]) was mapped to the v021 transcriptome via Jekely BLAST webserver; best hit was confirmed to be member of the TEKTIN family via reverse BLAST search on NCBI
[1]https://www.sciencedirect.com/science/article/pii/S0012160623001380

annotate tektin2

---

chunks/scaffold_7.gff3-01

NCBI sequence of Wnt2 was mapped to the v021 transcriptome via Jekely BLAST webserver.
https://bmcecolevol.biomedcentral.com/articles/10.1186/1471-2148-10-374

annotate wnt2

---

chunks/scaffold_6.gff3-01

Annotation: *dbh* (dopamine beta-hydroxylase)
**Gene:** *dbh* (dopamine beta-hydroxylase)
**Gene Nomenclature**: [HGNC](https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:2689)
**NCBI GeneBank ID:** [KJ855061.1](https://www.ncbi.nlm.nih.gov/nuccore/KJ855061.1/) (mRNA, complete cds)
**Annotated XLOC:** XLOC_056341
**Annotation Process:**
- Obtained mRNA cds from NCBI
- Mapped to P. dum. transcriptome assembly v021 using BLASTn (Jékely Lab): [Results](https://jekelylab.ex.ac.uk/blast/a92baa31-d9bf-4654-8723-f634622173ce) 
- Best hit (TCONS_00135235 XLOC_056341) > blastx on NCBI > confirmed
**Comments:** /

Annotation: dbh (dopamine beta-hydroxylase)

---

chunks/scaffold_10.gff3-01
chunks/scaffold_14.gff3

Sequence from [1] was blasted againt Pdum transcriptome 021, and hit was confirmed by reverse BLAST search on NCBI.
[1] Conzelmann, M., Williams, E.A., Krug, K. et al. The neuropeptide complement of the marine annelid Platynereis dumerilii. BMC Genomics 14, 906 (2013). https://doi.org/10.1186/1471-2164-14-906

annotate FMRFamide

---

chunks/scaffold_4.gff3-03

NCBI sequence of MIP/allatostatin B receptor (from [1]) was mapped to the v021 transcriptome via Jekely BLAST webserver; best hit had expect value 0.
[1] https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3657792/

Update scaffold_4.gff3-03 MIP/allatostatin B receptor

---

chunks/unplaced.gff3-05

NCBI sequence of MIP (from [1]) was mapped to v021 transcriptome  via Jekely lab BLAST server. Best hit was confirmed as MIP via reverse BLAST search on NCBI.
[1] https://pubmed.ncbi.nlm.nih.gov/23569279/

annotate myoinhibitory peptide

---

chunks/scaffold_2.gff3-04

NCBI sequence of hes1 from Gazave et al 2014 was mapped to the v021 transcriptome via Jekely BLAST webserver; best hit confirmed via blast on NCBI

annotate hes1

---

chunks/scaffold_13.gff3-01

Extensive gene model search in Platynereis and other nereids, and subsequent solid phylogenetic analysis using metazoan gene and nereid gene models of all fox related genes. Nereid annelids (Avir, Pdum) have only one foxL2 gene. Currently not on NCBI. Best hit: forkhead box L2 protein, partial [Lottia gigantea]

Annotate FoxL2

---

chunks/scaffold_25.gff3

Extensive gene model search, and subsequent solid phylogenetic analysis using metazoan gene models Already on NCBI: GenBank: ALS30887.1
There is a second 100% hit XLOC_036961 which I think is the same gene, and should removed. For now, we named both Frizzled-1/2/7

Annotate Frizzled-1/2/7

---

chunks/scaffold_2.gff3-01

lhx1/5 was mapped to the v021 transcriptome via Jekely BLAST webserver; best hit was confirmed to be member of the LIM/homeobox protein family via reverse BLAST search on NCBI

annotate lhx1/5
